FROM koide3/gtsam_points:jammy_gtsam4.3a0


# Install useful packages
RUN apt-get update && apt-get install -y vim wget git tmux 
# Install for cmake
RUN apt-get update && apt-get install -y make clang libboost-all-dev
# Install build packages
RUN apt-get update && apt install -y python3-colcon-common-extensions
# Install ros packages
RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-geodesy \
    ros-${ROS_DISTRO}-pcl-ros \
    ros-${ROS_DISTRO}-nmea-msgs \
    ros-${ROS_DISTRO}-libg2o \
    ros-${ROS_DISTRO}-cv-bridge \
    ros-${ROS_DISTRO}-eigen3-cmake-module

    # ros-${ROS_DISTRO}-geometry \
    # ros-${ROS_DISTRO}-rviz \


WORKDIR /root/ros2_ws/src

RUN git clone https://github.com/koide3/glim.git
RUN git clone -b release/4.3a0 https://github.com/borglab/gtsam.git
ADD . glim_ros2


WORKDIR /root/ros2_ws

ADD ./scripts ./scripts


CMD ["tmux"]